name: Mergability Check

on:
  push:
    branches-ignore:
      - master

jobs:
  setup-environment:
    name: Setup environment
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Installing node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.9.0

  lint:
    name: ESLint
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Get Yarn cache path
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/checkout@master
      - name: Load Yarn cache
        uses: actions/cache@master
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Installing dependencies
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile
      - run: yarn lint

  test-coverage:
    name: Test & Coverage Report
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - name: Get Yarn cache path
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/checkout@master
      - name: Load Yarn cache
        uses: actions/cache@master
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Installing top level dependencies
      - name: Installing top level dependencies
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile
      - name: Installing integration dependencies
        run: yarn install:integration
      - name: Run tests
        run: yarn test:coverage --ci
